

#Zuul routes: Here for /accounts path, we are routing to localhost:8081 with extra path after that:
zuul:
  routes:
    accounts-api:
      url: http://localhost:8081
 
#Ribbon is auto integrated with Zuul and for this exercise we are not using that:
ribbon:
  eureka:
    enabled: false
 
#Will start the gateway server @8080
server:
  port: 8080

# Spring Application Settings
spring:
  main:
    allow-bean-definition-overriding: true
