# We don not need this file anymore. Spring boot reads database configuration data only (don't know why) from application.yml or application.properties

#Spring Properties
spring:
  application:
    name: accounts-service

#Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}


#HTTP Server
server:
  port: 8081  # HTTP (Tomcat) port
  