
#HTTP Server
server:
  port: 8081  # HTTP (Tomcat) port

#Spring Properties
spring:
  application:
    name: accounts-service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/microservicesdemo
    username: root
    password: bcmc1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true

  
#Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}


